### PR TITLE
[BUG]: Fixed if else statement for when user enters other than "no" or "yes"

### PR DESCRIPTION
**Pull request by ankman007**
### Issue Description
Added conditions when user enters other than "no" or "yes" when the game ends inside of if else statement.

Solved Issue For #2 

### Screenshots

_Screenshot 1_

_Screenshot 2_

### CODE REVIEW

**Comment by ankman007** [comment]
@vedantterse Please review and let me know if I need to make few tweaks.

**Comment by vedantterse** [comment]
image
the changes you made in that whenever a value is given other than yes or no it although displays the message of error but continues the loop

**Comment by vedantterse** [comment]
hint: add a While loop and try with it.

**Comment by vedantterse** [comment]
Hello! Unfortunately, due to inactiveness we are closing this pull request also the issue has been resolved you can take a look at it 

you can anyways contribute to issues in this or any other issue in our repos! 

Thank you.

**Pull request closed without merging**
